// src/utils/livrosBiblia.js

export const nomesLivrosVelhoTestamento = {
    gn: "Gênesis",
    ex: "Êxodo",
    lv: "Levítico",
    nm: "Números",
    dt: "Deuteronômio",
    js: "Josué",
    jz: "Juízes",
    rt: "Rute",
    "1sm": "1 Samuel",
    "2sm": "2 Samuel",
    "1rs": "1 Reis",
    "2rs": "2 Reis",
    "1cr": "1 Crônicas",
    "2cr": "2 Crônicas",
    ed: "Esdras",
    ne: "Neemias",
    tb: "Tobias",
    jd: "Judite",
    est: "Ester (com acréscimos deuterocanônicos)",
    "1mc": "1 Macabeus",
    "2mc": "2 Macabeus",
    jo: "Jó",
    sl: "Salmos",
    pv: "Provérbios",
    ec: "Eclesiastes",
    ct: "Cântico dos Cânticos",
    sb: "Sabedoria",
    si: "Eclesiástico (ou Sirácida)",
    is: "Isaías",
    jr: "Jeremias",
    lm: "Lamentações",
    br: "Baruc",
    ez: "Ezequiel",
    dn: "Daniel (com acréscimos deuterocanônicos)",
    os: "Oséias",
    jl: "Joel",
    am: "Amós",
    ob: "Obadias",
    jn: "Jonas",
    mq: "Miqueias",
    na: "Naum",
    hc: "Habacuque",
    sf: "Sofonias",
    ag: "Ageu",
    zc: "Zacarias",
    ml: "Malaquias"
};

export const nomesLivrosNovoTestamento = {
    mt: "Mateus",
    mc: "Marcos",
    lc: "Lucas",
    jo: "João",
    at: "Atos dos Apóstolos",
    rm: "Romanos",
    "1co": "1 Coríntios",
    "2co": "2 Coríntios",
    gl: "Gálatas",
    ef: "Efésios",
    fm: "Filipenses",
    cl: "Colossenses",
    "1ts": "1 Tessalonicenses",
    "2ts": "2 Tessalonicenses",
    "1tm": "1 Timóteo",
    "2tm": "2 Timóteo",
    tt: "Tito",
    fm: "Filemom",
    hb: "Hebreus",
    tg: "Tiago",
    "1pe": "1 Pedro",
    "2pe": "2 Pedro",
    "1jo": "1 João",
    "2jo": "2 João",
    "3jo": "3 João",
    jd: "Judas",
    ap: "Apocalipse"
};
